#include<windows.h>
#include<iostream>
#include<conio.h>
#include<cstring>
#include<cstdio>
#include<ctime>
using namespace std;
int x=1,y=1,xz,gsx=8,gsy=8,pa,jc=0,sl=0,sy,q,mzz;
int nd,sd,e,sdm;
int gs,dq,ygs;
string mz;
int squp,jjup,slup;
int main()
{

 for(;;)
 {
    cout<<"1、打怪\n2、商店"<<endl;
    e=getch();system("cls");
    if(e==48+1)
    {
         cout<<"1、小僵尸\n2、北极熊\n3、恐龙\n4、哥斯拉\n5、SCP收容失效"<<endl;
        nd=getch();system("cls");
        gsx=8;
        gsy=8;
        pa=0;
        if(nd==48+1)
        {
            mz="小僵尸";
            gs=400;
            dq=30;
         }
        if(nd==48+2)
        {
            mz="北极熊";
            gs=1400;
            dq=100;
        }
        if(nd==48+3)
        {
            mz="恐龙";
            gs=3700;
            dq=320;
        }
        if(nd==48+4)
        {
            mz="哥斯拉";
            gs=7000;
            dq=600;
        }
        if(nd==48+5)
        {
            mz="SCP收容失效";
            gs=100000;
            dq=3000;
        }ygs=gs;
     for(int i=1;;i++)
     { 
      if(mzz!=1&&sy==1)cout<<"手雷未命中"<<endl;
      if(pa!=0)cout<<mz<<"减"<<pa<<"滴血"<<endl;
      cout<<mz<<"剩余"<<gs<<"滴血"<<endl;
      sy=0;
      for(int xx=1;xx<=15;xx++)
      { 
        for(int yy=1;yy<=15;yy++)
        {
            if(xx==x&&yy==y)
             {
                cout<<"你";yy++;
             }
            else if(xx==gsx&&yy==gsy)
             {
                cout<<"怪";yy++;
             }
            else cout<<".";
        }
        cout<<endl;
      }
      cout<<"w,s,a,d移动。1、使用手枪（无限子弹）";
      if(jc>=1)cout<<"2、使用狙击枪（"<<jc<<"发子弹）";
      if(sl>=1)cout<<"3、使用手雷（"<<sl<<"个）"<<endl;
      if(gs<=1000&&jc>=1&&sl>=1)cout<<"4、打击伤口（消耗狙击枪子弹和手雷）"<<endl;
       xz=getch();
       if(xz==119&&(x-1)!=0)x--;
       if(xz==115&&(x+1)!=16)x++;
       if(xz==97&&(y-1)!=0)y--;
       if(xz==100&&(y+1)!=16)y++;
       if(xz==49)
       {
        pa=50+rand()%30+squp*30;
        gs-=pa;
       }
       if(xz==50&&jc>=1)
       {
        pa=130+rand()%40+jjup*60;
        gs-=pa;
        jc--;
       }
       if(xz==51&&sl>=1)
       {
        mzz=rand()%4;sy=1;sl--;
        if(mzz==1||mzz==3)
        { 
        pa=300+rand()%30+slup*100;
        gs-=pa;
        mzz=1;
        } 
       }
       if(gs<=ygs/4&&jc>=1&&xz==52&&sl>=1)
       {
        pa=600+rand()%50;
        gs-=pa;
        jc--;
        sl--;
       }
       if(gs<=0)
       {
        system("cls");
        cout<<"You win!"<<endl;
        cout<<"获得"<<dq<<"个金币"<<endl; 
        q+=dq;
        Sleep(2000);system("cls");break;
       } 
       if(rand()%2+1==1)
       {
        if(gsy<y)gsy++;
        else if(gsx<x)gsx++;
        else if(gsy>y)gsy--;
        else if(gsx>x)gsx--;
       }
       if(gsx==x&&gsy==y)
        {
            system("cls");
         cout<<"Game over!";
        cout<<"你掉落了一半的金币！"<<endl;
        q/=2;
        Sleep(2000);system("cls");break;
        }
       system("cls");

      }
    }
    if(e==48+2)
    {
    	cout<<"你现在有"<<q<<"颗金币"<<endl; 
        cout<<"1、升级手枪2、升级狙击枪3、升级手雷\n4、购买十发狙击抢子弹5、购买十颗手雷"<<endl;
        sd=getch();
        if(sd==48+1)
        {
            cout<<"需要"<<(squp+1)*30<<"枚金币"<<endl;
            cout<<"1、升级"<<endl;
            sdm=getch();
            if(sdm==48+1&&q>=(squp+1)*30)
            {
                cout<<"购买成功！"<<endl;
                squp++;
                q-=(squp+1)*30;Sleep(2000);system("cls");
            }
            else
            {
                cout<<"无法购买！"<<endl;Sleep(2000);system("cls");
            }
        }
        if(sd==48+2)
        {
            cout<<"需要"<<(jjup+1)*50<<"枚金币"<<endl;
            cout<<"1、升级"<<endl;
            sdm=getch();
            if(sdm==48+1&&q>=(jjup+1)*50)
            {
                cout<<"购买成功！"<<endl;
                jjup++;
                q-=(jjup+1)*50;Sleep(2000);system("cls");
            }
            else
            {
                cout<<"无法购买！"<<endl;Sleep(2000);system("cls");
            }
        }
        if(sd==48+3)
        {
            cout<<"需要"<<(slup+1)*100<<"枚金币"<<endl;
            cout<<"1、升级"<<endl;
            sdm=getch();
            if(sdm==48+1&&q>=(slup+1)*100)
            {
                cout<<"购买成功！"<<endl;
                slup++;
                q-=(slup+1)*100;Sleep(2000);system("cls");
            }
            else
            {
                cout<<"无法购买！"<<endl;Sleep(2000);system("cls");
            }
        }
        if(sd==48+4)
        {
            cout<<"需要40元"<<endl;
            cout<<"1、购买"<<endl;
            sdm=getch();
            if(sdm==48+1&&q>=40)
            {
                cout<<"购买成功！"<<endl;
                jc+=10;
                q-=40;Sleep(2000);system("cls");
            }
            else
            {
                cout<<"无法购买！"<<endl;Sleep(2000);system("cls");
            }
        }
        if(sd==48+5)
        {
            cout<<"需要80元"<<endl;
            cout<<"1、购买"<<endl;
            sdm=getch();
            if(sdm==48+1&&q>=80)
            {
                cout<<"购买成功！"<<endl;
                sl+=10;
                q-=80;Sleep(2000);system("cls");
            }
            else
            {
                cout<<"无法购买！"<<endl;Sleep(2000);system("cls");
            }
        }
    }
 }

    return 0;
}
